data:extend({
  {
      name = "ei-plasma-cube-logo",
      type = "sprite",
      filename = ei_graphics_path.."graphics/128_placeholder.png",
      size = 128,
  },
  {
      name = "ei-uranium_patch",
      type = "sprite",
      filename = ei_graphics_entity_path.."uranium-patch.png",
      width = 567,
      height = 565,
  },
  {
      name = "ei-artifact",
      type = "sprite",
      filename = ei_graphics_entity_path.."alien-beacon_off-2.png",
      width = 512,
      height = 512,
  },
  {
      name = "ei-gate",
      type = "sprite",
      filename = ei_graphics_entity_2_path.."gate.png",
      width = 512*2,
      height = 512*2,
      scale = 0.5,
  },
  {
      name = "ei-train_progression",
      type = "sprite",
      filename = ei_graphics_other_path.."train_progression.png",
      width = 820,
      height = 410,
  },
  {
      name = "ei-robots",
      type = "sprite",
      filename = ei_graphics_other_path.."robots.png",
      width = 1166,
      height = 716,
      scale = 0.75,
  },
  {
      name = "ei-beacons",
      type = "sprite",
      filename = ei_graphics_other_path.."beacons.png",
      width = 981,
      height = 835,
      scale = 0.75,
  },
  {
      name = "ei-pipes",
      type = "sprite",
      filename = ei_graphics_path.."graphics/data-pipes/pipe-straight-vertical-single.png",
      width = 160,
      height = 160,
  },
  {
      name = "ei-induction_matrix",
      type = "sprite",
      filename = ei_graphics_tech_path.."induction-matrix-core.png",
      width = 256,
      height = 256,
  },
  {
      name = "ei-exotic_stabilizers",
      type = "sprite",
      filename = ei_graphics_entity_path.."alien-stabilizer.png",
      width = 512,
      height = 512,
  },
  {
      name = "ei-fission_reactors",
      type = "sprite",
      filename = ei_graphics_entity_path.."high-temperature-reactor.png",
      width = 512,
      height = 512,
  },
  {
      name = "ei-fusion_power",
      type = "sprite",
      filename = ei_graphics_other_path.."fusion.png",
      width = 1108,
      height = 794,
      scale = 0.75,
  },
  {
      name = "ei-black_hole",
      type = "sprite",
      filename = ei_graphics_tech_path.."black-hole.png",
      width = 256,
      height = 256,
  },
  {
      name = "ei-compilatron",
      type = "sprite",
      filename = ei_graphics_other_path.."compilatron.png",
      width = 64,
      height = 64,
  },

  -- Knowledge system
  {
      name = "ei-knowledge-gate",
      type = "sprite",
      filename = ei_graphics_tech_2_path.."gate.png",
      width = 256,
      height = 256,
      scale = 0.5,
  },
  {
      name = "ei-knowledge-crystal-accumulator-repair",
      type = "sprite",
      filename = ei_graphics_tech_2_path.."crystal-accumulator-repair.png",
      width = 256,
      height = 256,
      scale = 0.5,
  },
  {
      name = "ei-knowledge-farstation-repair",
      type = "sprite",
      filename = ei_graphics_tech_2_path.."farstation-repair.png",
      width = 256,
      height = 256,
      scale = 0.5,
  },
  {
      name = "ei-knowledge-farstation",
      type = "sprite",
      filename = ei_graphics_tech_2_path.."farstation.png",
      width = 256,
      height = 256,
      scale = 0.5,
  },
  {
      name = "ei-knowledge-alien-beacon-repair",
      type = "sprite",
      filename = ei_graphics_tech_2_path.."alien-beacon-repair.png",
      width = 256,
      height = 256,
      scale = 0.5,
  },
  {
      name = "ei-knowledge-bio-chamber",
      type = "sprite",
      filename = ei_graphics_tech_path.."bio-chamber.png",
      width = 256,
      height = 256,
      scale = 0.5,
  },
  {
      name = "ei-knowledge-bio_insulated-wire",
      type = "sprite",
      filename = ei_graphics_other_path.."bio_insulated-wire.png",
      width = 64,
      height = 64,
      scale = 2,
  },
  {
      name = "ei-knowledge-bio_energy-crystal",
      type = "sprite",
      filename = ei_graphics_other_path.."bio_energy-crystal.png",
      width = 64,
      height = 64,
      scale = 2,
  },
  {
      name = "ei-knowledge-bio_high-energy-crystal",
      type = "sprite",
      filename = ei_graphics_other_path.."bio_high-energy-crystal.png",
      width = 64,
      height = 64,
      scale = 2,
  },
  {
      name = "ei-knowledge-bio_hydrofluoric-acid",
      type = "sprite",
      filename = ei_graphics_other_path.."bio_hydrofluoric-acid.png",
      width = 64,
      height = 64,
      scale = 2,
  },
  {
      name = "ei-knowledge-bio_nitric-acid",
      type = "sprite",
      filename = ei_graphics_other_path.."bio_nitric-acid.png",
      width = 64,
      height = 64,
      scale = 2,
  },
  {
      name = "ei-knowledge-bio_electronic-parts",
      type = "sprite",
      filename = ei_graphics_other_path.."bio_electronic-parts.png",
      width = 64,
      height = 64,
      scale = 2,
  },
  {
      name = "ei-knowledge-bio_carbon-structure",
      type = "sprite",
      filename = ei_graphics_other_path.."bio_carbon-structure.png",
      width = 64,
      height = 64,
      scale = 2,
  },
  {
      name = "ei-knowledge-bio_magnet",
      type = "sprite",
      filename = ei_graphics_other_path.."bio_magnet.png",
      width = 64,
      height = 64,
      scale = 2,
  },
  {
      name = "ei-knowledge-bio_rocket-fuel",
      type = "sprite",
      filename = ei_graphics_other_path.."bio_rocket-fuel.png",
      width = 64,
      height = 64,
      scale = 2,
  },
  -- 3.1.0: alien tech tree nodes (scripts/control/alien_system.lua -> model.get_button_sprite)
  {
      name = "ei-knowledge-resonant-computation",
      type = "sprite",
      filename = ei_graphics_tech_path.."alien-computer-age-tech.png",
      width = 256,
      height = 256,
      scale = 0.5,
  },
  {
      name = "ei-knowledge-threshold-engineering",
      type = "sprite",
      filename = ei_void_engine_path.."void-engine.png",
      width = 256,
      height = 256,
      scale = 0.5,
  },
  -- 3.1.0: InformaTron pages of the Gaia hub systems
  {
      name = "ei-conduit",
      type = "sprite",
      filename = ei_path.."graphics/conduit/conduit-icon-big.png",
      width = 640,
      height = 640,
      scale = 0.2,
  },
  {
      name = "ei-data_center",
      type = "sprite",
      filename = ei_path.."graphics/cybernetics-facility/cybernetics-facility-icon-big.png",
      width = 640,
      height = 640,
      scale = 0.2,
  },
})