--====================================================================================================
--PRESET FOR MILESTONE MOD
--====================================================================================================

remote.add_interface("exotic-industries-milestones", {
    milestones_presets = function()
    return {
        ["Exotic Industries"] = {
            required_mods = {"exotic-space-industries"},
            milestones = {
                {type="group",      name="Science"},
                {type="item",       name="ei-dark-age-tech", quantity=1},
                {type="item",       name="ei-steam-age-tech", quantity=1},
                {type="item",       name="ei-electricity-age-tech", quantity=1},
                {type="item",       name="ei-computer-age-tech", quantity=1},
                {type="item",       name="ei-advanced-computer-age-tech", quantity=1},
                {type="item",       name="ei-alien-computer-age-tech", quantity=1},
                {type="item",       name="ei-quantum-age-tech", quantity=1},
                {type="item",       name="ei-fusion-quantum-age-tech", quantity=1},
                {type="item",       name="ei-exotic-age-tech", quantity=1},
    
                {type="group",      name="Ages of Technology"},
                {type="technology", name="ei-dark-age",  quantity=1},
                {type="technology", name="ei-steam-age",  quantity=1},
                {type="technology", name="ei-electricity-age",  quantity=1},
                {type="technology", name="ei-computer-age",  quantity=1},
                {type="technology", name="ei-quantum-age",  quantity=1},
                {type="technology", name="ei-exotic-age",  quantity=1},

                {type="group",      name="Materials and Resources"},
                {type="item",       name="iron-plate", quantity=1},
                {type="item",       name="copper-plate", quantity=1},
                {type="item",       name="steel-plate", quantity=1},
                {type="item",       name="ei-gold-ingot", quantity=1},
                {type="item",       name="ei-lead-ingot", quantity=1},
                {type="item",       name="ei-neodym-ingot", quantity=1},
                {type="item",       name="ei-exotic-ore", quantity=1},
                {type="item",       name="electronic-circuit", quantity=1},
                {type="item",       name="advanced-circuit", quantity=1},
                {type="item",       name="processing-unit", quantity=1},
                {type="item",       name="ei-eu-circuit", quantity=1},
                {type="item",       name="ei-electronic-parts", quantity=1},
                {type="item",       name="ei-rocket-parts", quantity=1},
                {type="item",       name="ei-high-tech-parts", quantity=1},
                {type="item",       name="ei-cpu", quantity=1},
                {type="item",       name="ei-magnet", quantity=1},
                {type="item",       name="ei-carbon-structure", quantity=1},
                {type="item",       name="ei-alien-resin", quantity=1},
                {type="item",       name="ei-bio-matter", quantity=1},
                {type="item",       name="ei-cryodust", quantity=1},
                {type="item",       name="ei-condensed-cryodust", quantity=1},
                {type="item",       name="ei-sus-plating", quantity=1},
                {type="item",       name="ei-odd-plating", quantity=1},
                {type="item",       name="ei-clean-plating", quantity=1},
                {type="item",       name="ei-eu-magnet", quantity=1},
                {type="item",       name="ei-plasma-cube", quantity=1},
    
                {type="group",      name="Transportation and Robots"},
                {type="item",       name="transport-belt", quantity=100},
                {type="item",       name="fast-transport-belt", quantity=100},
                {type="item",       name="express-transport-belt", quantity=100},
                {type="item",       name="ei-neo-belt", quantity=100},
                {type="item",       name="ei-steam-inserter", quantity=1},
                {type="item",       name="inserter", quantity=1},
                {type="item",       name="fast-inserter", quantity=1},
                {type="item",       name="bulk-inserter", quantity=1},
                {type="item",       name="ei-small-inserter", quantity=1},
                {type="item",       name="ei-big-inserter", quantity=1},
                {type="item",       name="ei-steam-basic-locomotive", quantity=1},
                {type="item",       name="ei-steam-advanced-locomotive", quantity=1},
                {type="item",       name="locomotive", quantity=1},
                {type="item",       name="car", quantity=1},
                {type="item",       name="tank", quantity=1},
                {type="item",       name="spidertron", quantity=1},
                {type="item",       name="logistic-robot", quantity=50},
                {type="item",       name="construction-robot", quantity=50},
                {type="item",       name="ei-cargo-bot", quantity=50},
                {type="item",       name="ei-construction-bot", quantity=50},
                {type="item",       name="ei-advanced-logistic-bot", quantity=50},
                {type="item",       name="ei-advanced-construction-bot", quantity=50},
                
                {type="group",      name="Power Machinery"},
                {type="item",       name="ei-burner-heater", quantity=1},
                {type="item",       name="ei-fluid-heater", quantity=1},
                {type="item",       name="boiler", quantity=1},
                {type="item",       name="ei-fluid-boiler", quantity=1},
                {type="item",       name="steam-engine", quantity=1},
                {type="item",       name="ei-combustion-turbine", quantity=1},
                {type="item",       name="nuclear-reactor", quantity=1},
                {type="item",       name="ei-high-temperature-reactor", quantity=1},
                {type="item",       name="solar-panel", quantity=1},
                {type="item",       name="ei-solar-panel-2", quantity=1},
                {type="item",       name="ei-solar-panel-3", quantity=1},
    
                {type="group",      name="Hightech Machinery"},
                {type="item",       name="ei-gate", quantity=1},
                {type="item",       name="ei-induction-matrix-core", quantity=1},
                {type="item",       name="ei-computer-core", quantity=1},
                {type="item",       name="ei-quantum-computer", quantity=1},
                {type="item",       name="ei-fusion-reactor", quantity=1},
                {type="item",       name="ei-matter-stabilizer", quantity=1},
                {type="item",       name="ei-accelerator", quantity=1},

                {type="group",      name="Space Flight"},
                {type="item",       name="rocket-silo", quantity=1},
                {type="item",       name="ei-holo-nauvis-orbit", quantity=1},
                {type="item",       name="ei-holo-moon", quantity=1},
                {type="item",       name="ei-holo-mars", quantity=1},
                {type="item",       name="ei-holo-gas-giant", quantity=1},
                {type="item",       name="ei-holo-uran", quantity=1},
                {type="item",       name="ei-holo-sulf", quantity=1},
                {type="item",       name="ei-holo-sun", quantity=1},
                {type="item",       name="ei-holo-asteroid", quantity=1},
    
                {type="group",      name="Kills"},
                {type="kill",       name="medium-biter",            quantity=1},
                {type="kill",       name="big-biter",               quantity=1},
                {type="kill",       name="behemoth-biter",          quantity=1},
                {type="kill",       name="behemoth-biter",          quantity=1000, next="x10"},
                {type="kill",       name="character",               quantity=1, next="x5"},
            }
        },
    }
end})